### ISSUE TITLE
Integrate python3 and python2 branches

### ISSUE THREAD

**Issue by chiahaoliu** [diffpy/diffpy.utils#8]
We already have a working ``python3`` branch and an alpha release from the branch.

It would be nice if we can merge current ``master``, which is python2, with ``python3`` branch to make two-way compatible.

**Comment by pavoljuhas** [comment]
Partially implemented in https://github.com/pavoljuhas/diffpy.utils/tree/support-py2-and-py3

## TODO

- [ ] review setup.py
- [ ] make sure .travis.yml tests all supported versions
- [ ] push test merge to a temporary branch
